from tkinter import *
#настройка окна
root = Tk()
root.title("Калькулятор успеваемости")
root.configure(bg='darkgray')
w = 400
h = 400
ws = root.winfo_screenwidth()
hs = root.winfo_screenheight()
x = (ws / 2) - (w / 2)
y = (hs / 2) - (h / 2)
root.geometry('%dx%d+%d+%d' % (w, h, x, y))
#строки текста
label = Label(text="Количество пятёрок:")
label.place(x=15, y=15)
entry = Entry()
entry.place(x=15, y=40, width=25, height=25)
label1 = Label(text="Количество четвёрок:")
label1.place(x=15, y=70)
entry1 = Entry()
entry1.place(x=15, y=95, width=25, height=25)
label2 = Label(text="Количество троек:")
label2.place(x=15, y=125)
entry2 = Entry()
entry2.place(x=15, y=150, width=25, height=25)
label3 = Label(text="Количество двоек:")
label3.place(x=215, y=15)
entry3 = Entry()
entry3.place(x=215, y=40, width=25, height=25)
label4 = Label(text="Общее количество учащихся:")
label4.place(x=215, y=70)
entry4 = Entry()
entry4.place(x=215, y=95, width=25, height=25)
label5 = Label(text="Н/А:")
label5.place(x=215, y=125)
entry5 = Entry()
entry5.place(x=215, y=150, width=25, height=25)
#тело
def button_click():
    y = float(entry.get())
    z = float(entry1.get())
    q = float(entry1.get())
    n = float(entry1.get())
    g = float(entry1.get())
    j = float(entry1.get())
#Процент успеваемости
    x = (y+z+q)
    x = round(x, 2)
#Процент качества знаний(2 эта типа 100%, типа умножить на 100%, это как умножить на 2 Я ПРОВЕРИЛ)
    v = (y+z)*2/g
    v = round(v, 2)
#Степень обученности учащихся (СОУ)
    b = (y * 100 + z * 64 + q * 36 + n * 16 + j * 7) / g
    b = round(b, 2)
    entry6.insert(END, x)
    entry7.insert(END, v)
    entry8.insert(END, b)
#кнопка для тела
button = Button(text="Рассчитать", command=button_click)
button.place(x=15, y=180, width=145, height=25)
label6 = Label(text="Процент успеваемости:")
label6.place(x=15, y=210)
entry6 = Entry()
entry6.place(x=15, y=235, width=175, height=25)
label7 = Label(text="Процент качества знаний:")
label7.place(x=15, y=265)
entry7 = Entry()
entry7.place(x=15, y=290, width=175, height=25)
label8 = Label(text="Степень обученности учащихся (СОУ):")
label8.place(x=15, y=320)
entry8 = Entry()
entry8.place(x=15, y=345, width=175, height=25)
root.mainloop()